version: "3.4"

volumes:
  var-lib-mysql:
  var-spool-centreon:

networks:
  oxyure-net:
    external:
      name: oxyure-net

services:
  #~ php-5.4.40:
    #~ build:
      #~ context: .
      #~ dockerfile: php-5.4.40.Dockerfile
    #~ depends_on:
     #~ - mariadb-10.1.26
    #~ image: oxyure/php-5.4.40:latest
    #~ entrypoint:
     #~ - /sbin/tini
     #~ - /entrypoint
    #~ container_name: php-fpm
    #~ hostname: php-fpm
    #~ networks:
      #~ oxyure-net:
          #~ ipv4_address: "172.30.0.40"

  #~ nginx-1.12.2:
    #~ build:
      #~ context: .
      #~ dockerfile: nginx-1.12.2.Dockerfile
    #~ depends_on:
     #~ - php-5.4.40
     #~ - mariadb-10.1.26
    #~ image: oxyure/nginx-1.12.2:latest
    #~ entrypoint:
     #~ - /sbin/tini
     #~ - /entrypoint
    #~ container_name: nginx
    #~ hostname: nginx
    #~ networks:
      #~ oxyure-net:
          #~ ipv4_address: "172.30.0.41"

  mariadb-10.1.26:
    build:
      context: .
      dockerfile: mariadb-10.1.26.Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    image: oxyure/mariadb-10.1.26:latest
    env_file: .env
    entrypoint:
     - /sbin/tini
     - /entrypoint
    container_name: mariadb
    hostname: mariadb
    networks:
      oxyure-net:
          ipv4_address: "172.30.0.42"
    volumes:
     - var-lib-mysql:/var/lib/mysql

  centreon:
    build:
      context: .
      dockerfile: centreon.Dockerfile
      args:
       http_proxy: ${http_proxy}
       https_proxy: ${https_proxy}
    depends_on:
     - mariadb-10.1.26
    image: oxyure/centreon:latest
    env_file: .env
    entrypoint:
     - /entrypoint
    container_name: centreon
    hostname: centreon
    networks:
      oxyure-net:
          ipv4_address: "172.30.0.100"
    volumes:
     - var-spool-centreon:/var/spool/centreon
