version: "3.4"

volumes:
  var-lib-mysql:
  var-spool-centreon:

networks:
  oxyure-net:
    external:
      name: oxyure-net

services:
  mariadb:
    build:
      context: .
      dockerfile: mariadb-10.1.26.Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    image: oxyure/mariadb:latest
    env_file: .env
    entrypoint:
     - /sbin/tini
     - -v
     - --
     - /entrypoint
    container_name: mariadb
    hostname: mariadb
    networks:
      oxyure-net:
          ipv4_address: "172.30.0.42"
    volumes:
     - var-lib-mysql:/var/lib/mysql

  centreon:
    build:
      context: .
      dockerfile: centreon.Dockerfile
      args:
       http_proxy: ${http_proxy}
       https_proxy: ${https_proxy}
    depends_on:
     - mariadb
    image: oxyure/centreon:latest
    env_file: .env
    entrypoint:
     - /sbin/tini
     - -v
     - --
     - /entrypoint
    container_name: centreon
    hostname: centreon
    networks:
      oxyure-net:
          ipv4_address: "172.30.0.100"
    volumes:
     - var-spool-centreon:/var/spool/centreon
