version: "3.4"

volumes:
  centreondb-var-lib-mysql:
  centreon-etc:
  centreon-centreon-www:

networks:
  centreon-net:
    external:
      name: centreon-net

services:
  centreondb:
    env_file: centreondb.env
    build:
      context: .
      dockerfile: centreondb.Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    image: oxyure/centreondb:latest
    env_file: centreondb.env
    entrypoint:
     - /sbin/tini
     - -g
     - -v
     - --
     - /entrypoint
    container_name: centreondb
    hostname: centreondb
    networks:
      centreon-net:
          ipv4_address: "172.36.0.42"
    volumes:
     - centreondb-var-lib-mysql:/var/lib/mysql

  centreon:
    env_file: centreon.env
    build:
      context: .
      dockerfile: centreon.Dockerfile
      args:
       http_proxy: ${http_proxy}
       https_proxy: ${https_proxy}
       CENTREON_CLIB_BRANCH: 1.4
       CENTREON_ENGINE_BRANCH: 2.0
       CENTREON_BROKER_BRANCH: 2.12
       CENTREON_CONNECTORS_BRANCH: 1.0
       CENTREON_CENTREON_BRANCH: 2.8.x
       CENTREON_TIMEZONE: Europe/Paris
    depends_on:
     - centreondb
    image: oxyure/centreon:latest
    env_file: centreon.env
    entrypoint:
     - /sbin/tini
     - -v
     - --
     - /entrypoint
    container_name: centreon
    hostname: centreon
    networks:
      centreon-net:
          ipv4_address: "172.36.0.100"
    ports:
     - "5555:80"
    volumes:
     - centreon-etc:/etc
     - centreon-centreon-www:/centreon/www

