version: "3.4"

volumes:
  centreondb-var-lib-mysql:
  centreon-etc:
  centreon-centreon-www:

networks:
  centreon-net:
    external:
      name: centreon-net

services:
  centreondb:
    env_file: centreondb.env
    build:
      context: centreondb
      dockerfile: centreondb.Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    image: oxyure/centreondb:latest
    entrypoint:
     - /entrypoint
    container_name: centreondb
    hostname: centreondb
    networks:
      centreon-net:
          ipv4_address: "172.36.0.42"
    volumes:
     - centreondb-var-lib-mysql:/var/lib/mysql

  centreon:
    env_file: centreon.env
    build:
      context: centreon
      dockerfile: centreon.Dockerfile
      args:
       http_proxy: ${http_proxy}
       https_proxy: ${https_proxy}
       CENTREON_CLIB_VERSION: ${CENTREON_CLIB_VERSION}
       CENTREON_ENGINE_VERSION: ${CENTREON_ENGINE_VERSION}
       CENTREON_BROKER_VERSION: ${CENTREON_BROKER_VERSION}
       CENTREON_CONNECTORS_VERSION: ${CENTREON_CONNECTORS_VERSION}
       CENTREON_CENTREON_VERSION: ${CENTREON_CENTREON_VERSION}
       CENTREON_TIMEZONE: ${CENTREON_TIMEZONE}
    depends_on:
     - centreondb
    image: oxyure/centreon:latest
    entrypoint:
     - /entrypoint
    container_name: centreon
    hostname: centreon
    networks:
      centreon-net:
          ipv4_address: "172.36.0.100"
    ports:
     - "5555:80"
    volumes:
     - centreon-etc:/etc
     - centreon-centreon-www:/centreon/www

