version: "3.4"

volumes:
  mariadb-var-lib-mysql:
  centreon-etc:
  centreon-usr-local-www:

#~ networks:
  #~ centreon-net:
    #~ external:
      #~ name: centreon-net

services:
  mariadb:
    build:
      context: .
      dockerfile: mariadb-10.1.26.Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    image: oxyure/mariadb:latest
    env_file: .env
    entrypoint:
     - /sbin/tini
     - -g
     - -v
     - --
     - /entrypoint
    container_name: mariadb
    hostname: mariadb
    #~ networks:
      #~ centreon-net:
          #~ ipv4_address: "172.36.0.42"
    volumes:
     - mariadb-var-lib-mysql:/var/lib/mysql

  centreon:
    build:
      context: .
      dockerfile: centreon.Dockerfile
      args:
       http_proxy: ${http_proxy}
       https_proxy: ${https_proxy}
    depends_on:
     - mariadb
    image: oxyure/centreon:latest
    env_file: .env
    entrypoint:
     - /sbin/tini
     - -v
     - --
     - /entrypoint
    container_name: centreon
    hostname: centreon
    #~ networks:
      #~ centreon-net:
          #~ ipv4_address: "172.36.0.100"
    ports:
     - "5555:80"
    volumes:
     - centreon-etc:/etc
     - centreon-usr-local-www:/usr/local/www

